import type { Metadata } from 'next'
import { Inter, Martel} from 'next/font/google'
import './globals.css'

const martel = Martel({ weight: ["400", "700", "900"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Funtec',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={martel.className}>{children}</body>
    </html>
  )
}
